### ISSUE TITLE
fail of task "ansible-samba : samba_users | adding samba users to samba groups"

### ISSUE THREAD

**Issue by BeckerFrank** [mrlesmithjr/vagrant-ansible-gerrit-lab#3]
I get the following error when I run vagrant up with vagrant 1.9.3 and virtual box 5.1.18

==> samba: PLAY [Build AD for LDAP] *******************************************************
==> samba: 
==> samba: TASK [Gathering Facts] *********************************************************
==> samba: ok: [samba]
==> samba: 
==> samba: TASK [ansible-isc-dhcp : debian | Installing DHCP Packages] ********************
==> samba: skipping: [samba]
==> samba: 
==> samba: TASK [ansible-isc-dhcp : redhat | Installing DHCP Packages] ********************
==> samba: skipping: [samba]
==> samba: 
==> samba: TASK [ansible-isc-dhcp : redhat | Ensuring DHCP Service is Enabled] ************
==> samba: skipping: [samba]
==> samba: 
==> samba: TASK [ansible-isc-dhcp : config | Configuring DHCP Service] ********************
==> samba: skipping: [samba]
==> samba: 
==> samba: TASK [ansible-ntp : debian | installing packages] ******************************
==> samba: ok: [samba] => (item=[u'ntp'])
==> samba: 
==> samba: TASK [ansible-ntp : debian | configuring ntp] **********************************
==> samba: changed: [samba]
==> samba: 
==> samba: TASK [ansible-ntp : redhat | installing packages] ******************************
==> samba: skipping: [samba] => (item=[]) 
==> samba: 
==> samba: TASK [ansible-ntp : redhat | installing packages] ******************************
==> samba: skipping: [samba] => (item=[]) 
==> samba: 
==> samba: TASK [ansible-ntp : redhat | configuring ntp] **********************************
==> samba: skipping: [samba]
==> samba: 
==> samba: TASK [ansible-ntp : redhat | ensuring ntpd service is started and enabled on boot] ***
==> samba: skipping: [samba]
==> samba: 
==> samba: TASK [ansible-samba : debian | installing pre-reqs] ****************************
==> samba: changed: [samba] => (item=[u'acl', u'dnsutils', u'krb5-user', u'python-glade2', u'samba', u'samba-common', u'smbldap-tools', u'system-config-samba'])
==> samba: 
==> samba: TASK [ansible-samba : samba_groups | ensuring groups exist] ********************
==> samba: changed: [samba] => (item=samba_groups)
==> samba: 
==> samba: TASK [ansible-samba : samba_users | adding samba users to samba groups] ********
==> samba: fatal: [samba]: FAILED! => {"failed": true, "msg": "subelements lookup expects a dictionary, got 'samba_users'"}
==> samba: 
==> samba: RUNNING HANDLER [ansible-ntp : restart ntp] ************************************
==> samba: 	to retry, use: --limit @/vagrant/playbook.retry
==> samba: 
==> samba: PLAY RECAP *********************************************************************
==> samba: samba                      : ok=5    changed=3    unreachable=0    failed=1   
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by mrlesmithjr** [comment]
@BeckerFrank Thanks for pointing this out. Looks like there are a few issues now. I have not used this in a while but will do some cleanup and see if it gets sorted out.
