### ISSUE TITLE
Getting  msg": "AnsibleUndefinedVariable: 'list object' has no attribute 'kerberos_realm'

### ISSUE THREAD

**Issue by venkateshmadala** [mrlesmithjr/vagrant-ansible-gerrit-lab#6]
Hi, I am getting below issue while bringing up the vagrant machine. below is the issue snippet. I tried to define this realm value in playbook.yml but it is not helpful. can you please help me in resolving this issue.  
    samba: TASK [ansible-samba : config_samba | configuring sam
ba] ************************
    samba: fatal: [samba]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'list object' has no attribute 'kerberos_realm'"}
    samba:      to retry, use: --limit @/vagrant/playbook.retry

**Comment by mrlesmithjr** [comment]
@venkateshmadala Thanks for reporting this. Looks like most of this is pretty outdated and will need to be refactored a bit. But as time permits, I will try to get it all sorted out.
